### ISSUE TITLE
"EMPTY" values in dashboard

### ISSUE THREAD

**Issue by alex-geopro** [amplitude/Amplitude-TypeScript#583] opened 2023-09-12 20:03 UTC
I'm using the browser sdk typescript 2.2.3 on a brand new amplitude project.  I've put the browser sdk snippet script in my web app, with default config, and I'm seeing ~19 user attributes on each user with value `EMPTY`.

I expected to only see attributes with actual values.  On other amplitude projects using the now legacy amplitude client I don't see this behaviour.

<img width="554" alt="Screen Shot 2023-09-12 at 1 03 15 PM" src="https://github.com/amplitude/Amplitude-TypeScript/assets/144632814/83e48930-0a33-4b11-a116-3cb442be33ec">

```
    <script type="text/javascript">
      !function(){"use strict";!function(e,t){var n=e.amplitude||{_q:[],_iq:{}};if(n.invoked)e.console&&console.error&&console.error("Amplitude snippet has been loaded.");else{var r=function(e,t){e.prototype[t]=function(){return this._q.push({name:t,args:Array.prototype.slice.call(arguments,0)}),this}},s=function(e,t,n){return function(r){e._q.push({name:t,args:Array.prototype.slice.call(n,0),resolve:r})}},o=function(e,t,n){e[t]=function(){if(n)return{promise:new Promise(s(e,t,Array.prototype.slice.call(arguments)))}}},i=function(e){for(var t=0;t<m.length;t++)o(e,m[t],!1);for(var n=0;n<g.length;n++)o(e,g[n],!0)};n.invoked=!0;var u=t.createElement("script");u.type="text/javascript",u.integrity="sha384-QhN12IHEJCDzzlNZ/ugu3iCq5jVI1saLR0QXlVfubYxdHb8NhKqgMhr9KeruyviR",u.crossOrigin="anonymous",u.async=!0,u.src="https://cdn.amplitude.com/libs/analytics-browser-2.2.3-min.js.gz",u.onload=function(){e.amplitude.runQueuedFunctions||console.log("[Amplitude] Error: could not load SDK")};var a=t.getElementsByTagName("script")[0];a.parentNode.insertBefore(u,a);for(var c=function(){return this._q=[],this},p=["add","append","clearAll","prepend","set","setOnce","unset","preInsert","postInsert","remove","getUserProperties"],l=0;l<p.length;l++)r(c,p[l]);n.Identify=c;for(var d=function(){return this._q=[],this},f=["getEventProperties","setProductId","setQuantity","setPrice","setRevenue","setRevenueType","setEventProperties"],v=0;v<f.length;v++)r(d,f[v]);n.Revenue=d;var m=["getDeviceId","setDeviceId","getSessionId","setSessionId","getUserId","setUserId","setOptOut","setTransport","reset","extendSession"],g=["init","add","remove","track","logEvent","identify","groupIdentify","setGroup","revenue","flush"];i(n),n.createInstance=function(e){return n._iq[e]={_q:[]},i(n._iq[e]),n._iq[e]},e.amplitude=n}}(window,document)}();
      amplitude.init('<apiKey>', { 
        defaultTracking: true,
        cookieOptions: {
          sameSite: 'None',
          secure: true
        }
      })
```

**Comment by yuhao900914** [comment] 2023-09-13 00:34
Hi @alex-geopro, Thanks for choosing amplitude. 
Those `EMPTY` values are for web attribution, which means it's direct traffic. 

Those are undefined/no initial campaign parameters for first-touch attribution. The default value is "EMPTY.
Check [here](https://www.docs.developers.amplitude.com/data/sdks/browser-2/#tracking-default-events) for more details. 

Do any of those attributions have an actual value we didn't catch?  If yes, can you provide the website and the reproducing method, which will be helpful for debugging? Thanks.

**Comment by alex-geopro** [comment] 2023-09-13 00:46
Hi @yuhao900914 I don't think those EMPTY values should be there.  They're not there on my projects using your previous SDK. Why the change in behaviour? see attached.

<img width="507" alt="Screenshot 2023-09-12 at 5 46 26 PM" src="https://github.com/amplitude/Amplitude-TypeScript/assets/144632814/8688564c-c2cb-4184-b35c-f94a8bcad791">

**Comment by yuhao900914** [comment] 2023-09-13 22:42
The old SDK has a different behavior from the new SDK. 
For the legacy SDK, it only sets the value while it's not empty. [Reference](https://github.com/amplitude/Amplitude-JavaScript/blob/main/src/amplitude-client.js#L788). 
Closing this since it's not a bug.

**Closed by yuhao900914** 2023-09-13 22:42 UTC
Labels: bug

**Comment by yuhao900914** [comment] 2023-09-13 22:44
Please check [here](https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/migration/#behavior) for the different behavior.

**Comment by alex-geopro** [comment] 2023-09-13 22:47
Thanks.  Can you explain why the new behaviour? It seems undesirable to
me.  It doesn't seem to make sense to show these when there are no values.

Also: "Default value for all init attribution is Empty and configurable",
does this mean I can configure it not to have a default value, so that
these do not show up? If so how?
