### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'this.config.userId = userId')

### ISSUE THREAD

**Issue by RubenMateus** [amplitude/Amplitude-TypeScript#171] opened 2022-08-04 15:43 UTC
## Summary

So I have this issue that all of a sudden started happening:

`TypeError: undefined is not an object (evaluating 'this.config.userId = userId')`

I can confirm the userId is being sent correctly and I am calling the init before.
Any ideas of what is happening?

**Comment by yuhao900914** [comment] 2022-08-04 17:45
Hi @RubenMateus, 
Thanks for using the amplitude typescript SDK.
Can you share with me the code snippet in order to reproduce this issue?

**Comment by RubenMateus** [comment] 2022-08-05 09:03
Hi @yuhao900914 

this is the code.
```
useEffect(() => {
    if (!id) {
        return
    }
    setUserId(id)
}, [id])
```
And i am also doing Init even before this hooks is called.

**Comment by korokd** [comment] 2022-08-10 20:51
Exact same issue here, semi identical hook even.

```tsx
  useEffect(() => {
    setUserId(user?.id)
  }, [user])
```

**Comment by kevinpagtakhan** [comment] 2022-08-10 20:56
Thanks all! This is caused by `init()` taking too long after we introduced async storage interface. We are actively working on a fix for this issue.

**Closed** 2022-08-12 21:50 UTC
Labels: bug
