### ISSUE TITLE
Unable to install package '@amplitude/analytics-browser' due to a 404 error

### ISSUE THREAD

**Issue by RunyShark** [amplitude/Amplitude-TypeScript#490] opened 2023-07-14 20:47 UTC
## Expected Behavior
I expected the installation of the "@amplitude/analytics-browser" package to complete successfully without any errors.

## Current Behavior
 I encountered an error during the installation process. The specific error message I received was a 404 Not Found error related to the "@amplitude/plugin-page-view-tracking-browser@^2.0.4" dependency.

## Steps to Reproduce
1. Run the command "npm install @amplitude/analytics-browser" in a  project directory.
2. Observe the error message and the 404 Not Found error related to the "@amplitude/plugin-page-view-tracking-browser@^2.0.4" dependency.

![image](https://github.com/amplitude/Amplitude-TypeScript/assets/92100746/06c86b83-361a-4da6-8267-927706f4cd89)
![image](https://github.com/amplitude/Amplitude-TypeScript/assets/92100746/be2670fd-8175-401d-889d-37ca8c79f7c5)

## Environment
- JS SDK Version:  "@amplitude/analytics-browser": "^2.1.2",
- Installation Method: NPM

With: @isc-joserodriguez

**Comment by yuhao900914** [comment] 2023-07-17 07:45
Hi @RunyShark, 
Thanks for choosing Amplitude. I cannot reproduce it on my side. 
<img width="481" alt="Screen Shot 2023-07-17 at 12 42 43 AM" src="https://github.com/amplitude/Amplitude-TypeScript/assets/13028329/9b0cb2f2-98a6-4339-909e-da512bb77704">

You can check  "@amplitude/plugin-page-view-tracking-browser@^2.0.4"  exists in [npm](https://www.npmjs.com/package/@amplitude/plugin-page-view-tracking-browser) and it's the latest version. 

I feel that's more towards an issue on npm at that time. Please try again and see if that still happen.

**Comment by yuhao900914** [comment] 2023-07-17 20:16
We also noticed that On 07/14 there has several npm error in our internal team. But it works again afterward. Pretty sure this is an npm issue. Closing this ticket.

**Closed by yuhao900914** 2023-07-17 20:16 UTC
Labels: bug
