### ISSUE TITLE
The event that occurred in 'amplitude-ma-ts' appears as the event that occurred in 'amplitude-ts'

### ISSUE THREAD

**Issue by sanghunka** [amplitude/Amplitude-TypeScript#302] opened 2022-12-26 09:57 UTC
Check out [this](https://community.amplitude.com/data-instrumentation-57/the-event-that-occurred-in-amplitude-ma-ts-appears-as-the-event-that-occurred-in-amplitude-ts-1697)

In my react web app, I only installed amplitude marketing-analytics-browser SDK.(amplitude-ma-ts)

But when I saw user look up, there are events that have library properties ‘amplitude-ts’
the attached screenshot is what I tested. I fired 2 events consecutively in the same environment (same device+same browser). But their library properties are not identical.

I want to know if this error has been fixed. Is it a safer choice to use library amplitude-ts instead of amplitude-ma-ts?"

## Expected Behavior

Library name that I installed

## Current Behavior

Library name that I didn't install

## Steps to Reproduce

- npm 

## Environment
- JS SDK Version: 
    - Amplitude-ma-ts/0.2.9
    - Amplitude-ma-ts/0.3.3
    - Both versions have the same error.
- Installation Method: 
    - npm 
- Browser and Version: 
    - Chrome 108.0.0.0

**Comment by qingzhuozhen** [comment] 2023-01-06 01:15
Hi @sanghunka Thanks for raising this up. The amplitude-ma-ts package is actually a wrapped package including amplitude-ts and couple ma plugins. Looking at the two events in the example, it seems the first two events and one guess is when the first event happen the ma context plugin is not loaded yet while when the second event come in the plugin was loaded and got into effect. Are all the events after with the correct library name? cc @kevinpagtakhan

**Comment by sanghunka** [comment] 2023-01-10 14:04
Hi @qingzhuozhen 

> Are all the events after with the correct library name?

No. Actually, there is no pattern. Some events have 'amplitude-ma-ts' user properties and other events have 'amplitude-ts' user properties randomly. 

I can share my amplitude project ID.

**Comment by kevinpagtakhan** [comment] 2023-01-10 18:26
Hi @sanghunka! Do you mind sharing a code sample so I can try to reproduce on my end?

**Comment by kevinpagtakhan** [comment] 2023-01-11 08:44
Hi @sanghunka, i tried running different scenarios on the browser and was not able to reproduce yet. We have light integration testing for marketing analytics SDK and we do not see the inconsistencies there either. If you can provide a code sample or a repo where I can pull and run, that would be super helpful on our part to investigate this issue further.

**Comment by justin-fiedler** [comment] 2023-04-27 00:05
Marking as resolved as we are unable to reproduce. Please reopen if you can provide steps to reproduce or a code example. Thank you

**Closed by justin-fiedler** 2023-04-27 00:05 UTC
Labels: bug
