### ISSUE TITLE
Amplitude Logger [Error]: Converting circular structure to JSON errors occurring after updating to version 2

### ISSUE THREAD

**Issue by keegan-kelly-prometheum** [amplitude/Amplitude-TypeScript#516] opened 2023-08-01 18:07 UTC
## Expected Behavior

Amplitude Logger [Error]: Converting circular structure to JSON errors do not occur.

## Current Behavior

On version 2.1.3, interacting with form elements that have the `id` attribute equal "name" will cause Amplitude Logger to log "Converting circular structure to JSON" errors when the user interacts with the form. Changing the `id` to any other string will resolve the issue.

```
<input id="name" type="text" maxlength="95" value="Name">
```

## Possible Solution

It appears this issue only happens if the `id` is the string `"name"` on v2.1.3. This does not seem to be an issue on v1.11.0.

## Steps to Reproduce

1. Using `@amplitude/analytics-browser` v2.1.3
2. Create a `form` that has an `input` where the `id="name"`.
3. Add text to the `input`
4. Notice when the `input` is no longer focused the following error will appear:

![circular-structure](https://github.com/amplitude/Amplitude-TypeScript/assets/114938905/ada3f053-9fa4-480b-b6a6-ba72a9a079c3)

![error](https://github.com/amplitude/Amplitude-TypeScript/assets/114938905/eaab848c-3302-4100-84ed-bded3254d509)

## Environment
- JS SDK Version: 
- Installation Method: NPM 
- Browser and Version: Chrome 115

**Comment by yuhao900914** [comment] 2023-08-02 16:47
Hi @keegan-kelly-prometheum ,
Thanks for using amplitude, I tried the form interaction with[ this example.](https://github.com/amplitude/Amplitude-TypeScript/pull/518/files) However, I'm not able to reproduce the circular issue. Do you mind sharing with me your code snippet related to the form?
Thanks.

**Comment by yuhao900914** [comment] 2023-08-02 20:42
@keegan-kelly-prometheum 
I'm not able to reproduce with `<input type="text" id="name" name="name" maxlength="95" value="Name">` neither.
I just merged the example. Please try to run the example [here](https://github.com/amplitude/Amplitude-TypeScript/tree/main/examples/browser/html-app).

**Comment by daniel-covelli** [comment] 2023-08-24 19:26
I think the issue is when you have an onSubmit handler which then fires an amplitude request.

**Comment by yuhao900914** [comment] 2023-09-01 06:19
@keegan-kelly-prometheum  @daniel-covelli  this issue should be fixed with the latest release, v2.2.3 with [this fix](https://github.com/amplitude/Amplitude-TypeScript/commit/80816c92b64d3e839688c7654c08c1503501e2ed).
I will close this issue now. Feel free to reopen the issue if still happening. 

Thanks.

**Closed by yuhao900914** 2023-09-01 06:19 UTC
Labels: bug
